#!/bin/bash
#
#
#
echo -n "Sisesta täisarv: "
read arv
summa=0
while [ $arv -ne 0 ]
do
        jaak=$(($arv % 10))
        summa=$(($summa + $jaak))
        arv=$(($arv / 10))
done
echo "antud arvu numbrite summa on:$summa"
#
#
#lõpp

